### ISSUE TITLE
[Bug]: The vanilla EXP system doesn't work!

### ISSUE THREAD

**Issue by ECHOSAN11** [magemonkeystudio/fabled#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Im using fabled-1.0.4-R0.1-20241114.071356-1, with minecraft version 1.20.1.
when i input this plugin to server, the vanilla exp system doesn't work.
I only want to use skillapi. is there any way to do it?

### Environment

```markdown
- Server Software: arclight-forge-1.20.1-1.0.5.jar
- Fabled Version: fabled-1.0.4-R0.1-20241114.071356-1.jar
- Codex Version: codex-1.0.1-R0.15-20241118.024345-1.jar
- Plugins: citizens coreprotect skript nametagedit imageframe treefeller
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by goflishMC** [comment]
I'm a little confused about what you are asking. Are you wanting to only use experience/levels from Fabled?

**Comment by ECHOSAN11** [comment]
no i want to use minecraft vanilla exp system.

**Comment by goflishMC** [comment]
go into config.yml and set `level-bar` to `none`

**Comment by ECHOSAN11** [comment]
it works! thank you very much....
