### ISSUE TITLE
[Enhancement] New Condition: Colors

### ISSUE THREAD

**Issue by goflishMC** [magemonkeystudio/fabled#147]
This condition would check the color of the entity before executing.

Options:

Icon Key: <key>
Mana: true/false: does this trigger check for mana cost
Cooldown: true/false Does this trigger check if is on cooldown
Color: drop down list

**Comment by Travja** [comment]
Checking the color of the entity... as in the color of sheep? Since they're the only colorable entity? Or is there some other color we'd want to be checking for this?

**Comment by goflishMC** [comment]
> Checking the color of the entity... as in the color of sheep? Since they're the only colorable entity? Or is there some other color we'd want to be checking for this?

sheep

**Comment by Travja** [comment]
Sheep and Shulkers are supported
