### ISSUE TITLE
[Bug] Proskillapi's life system is incompatible with health_ Boost is the vanilla effect of minecraft

### ISSUE THREAD

**Issue by luoxiawuchen** [magemonkeystudio/fabled#273]
**Is your feature request related to a problem? Please describe.**

When the health system is enabled, I found that it cannot be superimposed with the health_boost effect of minecraft, and will eventually be overwritten with the life recorded by ProSK plugin. I hope it can be compatible with the potion effect of minecraft

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lordsrubka5** [comment]
If possible, as always, making a config option if we want this feature or not.
If this goes through it should also apply to absorption hearts.
The config option is needed here because maybe someone wants extra buffs
to be raw health increase and some others might want it to be a percentage.

**Comment by Travja** [comment]
This probably also relates to #473

**Comment by Travja** [comment]
https://mahto.id/chat-exporter?url=https://cdn.discordapp.com/attachments/832365298824511509/1263362897476583474/yolo_149-divinity-request-transcript.html?ex=6699f5e2&is=6698a462&hm=9f2126f6df7fb26070597ac7494dc48efbde7fcd5ab2292397a50e046d4fc22d&

For context, here is a related ticket from Discord
