### ISSUE TITLE
[Enhancement] Moon Phase condition

### ISSUE THREAD

**Issue by Kuba663** [magemonkeystudio/fabled#561]
So moon-based powers sometimes happen and they happened at the server I work for but right now I (and maybe someone else idk) can't really balance them around moon phases.

**Solution: Moon phase condition**
A condition that executes when it matches the phase of the moon described in the skill.

**Comment by iomatix** [comment]
![image](https://github.com/promcteam/proskillapi/assets/13110161/ceb8a412-dbcf-42d9-a79b-217c2d998d69)

I guess it is possibe with something like that ... but only if the client moon phases are synced with time on the server so.. if the server contains data regarding the number of days has passed _(in e.g. is **wholeTimeHasPassed**)_ until now() or time in ms/seconds etc. so....

There are 8 phases of the moon.
```
numberDays=wholeTimeHasPassed/theOneDayTime; 
moonPhase=(enum) getMoonPhase(days%8); // -> e.g. 8 enums to choose from and get the phase by some function ... 
```
theOneDayTime -> the time of the one single day may vary so shouldn't be implemented as constant cuz some plugins may interfere... like [CustomTime](https://www.spigotmc.org/resources/customtime.81364/)
