### ISSUE TITLE
[Enhancement] rotate armor stand and name armor stand

### ISSUE THREAD

**Issue by ronyan149** [magemonkeystudio/fabled#725]
- I think we need to add the ability to rotate the entire armor stand, not just individual parts of it. Rotating the entire armor stand could create many interesting models or effects.
- Also, the name of the armor stand cannot use "value" and even colors like &f, &6, &b, etc.

**Comment by Travja** [comment]
I just added relative pitch/yaw positioning to the Warp mechanics. Can you let me know if this will work for your use case here?

**Comment by ronyan149** [comment]
it doesn't work if armorstand has "marker:true"

**Comment by Travja** [comment]
Marker armor stands are a little different and not always compatible with things. I might be able to work around it, but in my mind that's not a huge concern

**Comment by Travja** [comment]
I added a bit of work-around code, if you could try it out. Build will be live on Discord shortly.
