### ISSUE TITLE
[Bug]: Particles Error

### ISSUE THREAD

**Issue by 3Lord3** [magemonkeystudio/fabled#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Lots of errors from particles. Full logs take up 154 ​​MB
If you change the particles in the skill file to those used in /particle, then there will be no error.

### Expected Behavior

Particles in the editor will be correctly converted into game particles

### Steps To Reproduce

1. Create skill with Particle Animation
2. Set any particle
3. Use skill

### Environment

```markdown
- Server Software: Purpur 1.20.6-2227-79d199c (MC: 1.20.6)*
- Fabled Version: 1.0.0-R0.32-SNAPSHOT
- Codex Version: 1.0.0-R0.17-SNAPSHOT
- Plugins: Paper Plugins: (3): Codex, Divinity, Fabled | Bukkit Plugins: (1): spark
```

### latest.log

https://pastebin.com/MZ1NzcW7

**Comment by Travja** [comment]
See https://discord.com/channels/818973833570680882/818973931570069584/1245806084195880971

**Comment by Travja** [comment]
Aside from that, you're saying the values in the editor aren't working?

**Comment by 3Lord3** [comment]
> See https://discord.com/channels/818973833570680882/818973931570069584/1245806084195880971

Can you show me what's there? I don't use Discord

> Aside from that, you're saying the values in the editor aren't working?

Editor gives me this:
`particle: Villager happy`
but for this to work it needs to be changed to
`particle: 'happy_villager'`

**Comment by 3Lord3** [comment]
The Slow potion effect also does not work. The editor outputs Slow, but the effect requires Slowness. No error, but I think it's the same problem

**Comment by Travja** [comment]
The editor should now be showing the proper names for things for 1.20.6

**Comment by 3Lord3** [comment]
Yes, it works for 1.20.6. But now I upgraded to version 1.20.4 and I get the same error. What to do about it?

Server: git-Purpur-2176 (MC: 1.20.4)
Plugins: Paper Plugins: (3): Codex, Divinity, Fabled | Bukkit Plugins: (5): LibsDisguises, MythicMobs, PlaceholderAPI, ProtocolLib, spark
Codex and Fabled of the same versions

Log:
[latest.log](https://github.com/user-attachments/files/15777608/latest.log)

**Comment by Travja** [comment]
Unfortunately the editor only operates on major versions at the moment. Spigot made a pretty big change to the particle/enchantment/sound/etc api on the 1.20.6 update that makes those incompatible. Our goal is to be up to date and compatible primarily with the latest versions of each major release.

**Comment by Travja** [comment]
Villager happy technically isn't an option anymore. I just need to update the default for the particle option
