### ISSUE TITLE
[Bug]: Updating castbar

### ISSUE THREAD

**Issue by 3Lord3** [magemonkeystudio/fabled#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

If you create items with abilities, when they are removed, the abilities remain in the castbar. This can be fixed by reconnecting the server

### Expected Behavior

Castbar update

### Steps To Reproduce

1. Create class with ability
2. Create some items with abilities
3. Get this items
4. Check castbar for new abilities
5. Drop items with abilities
6. Check castbar

### Environment

```markdown
- Server Software: Purpur 1.20.6-2227-79d199c (MC: 1.20.6)*
- Fabled Version: 1.0.0-R0.32-SNAPSHOT
- Codex Version: 1.0.0-R0.17-SNAPSHOT
- Plugins: Paper Plugins: (3): Codex, Divinity, Fabled | Bukkit Plugins: (1): spark
```

**Comment by Travja** [comment]
If I understand what you're saying, items that give skills or other buffs (through Divinity) don't remove their effects when dropping the item? I have another report of the same thing, but I've been unable to reproduce it. Have you tried on a server software other than Purpur?

**Comment by 3Lord3** [comment]
> If I understand what you're saying, items that give skills or other buffs (through Divinity) don't remove their effects when dropping the item? I have another report of the same thing, but I've been unable to reproduce it. Have you tried on a server software other than Purpur?

Right. I got three abilities from three sticks. I threw them out, but the abilities remained on the list. But I can't use them anymore
![изображение](https://github.com/magemonkeystudio/fabled/assets/62335161/2a893286-a489-449e-adb9-d58ce357d3f6)
I haven't tried this on other server software

**Comment by Travja** [comment]
Ah. Okay. That helps. At least it's preventing you from using it. I'll have to take a look and see what I can do to get the action bar list to update

**Comment by 3Lord3** [comment]
Update: If an item with abilities is in first slot and the player dies, all abilities will be retained after death. They can be used. This goes away if you change the slot, but since first slot is automatically selected after death, the abilities remain. I think this goes back to the original problem.
Tested in survival mode without OP on two players. Server and plugins versions are the same
