### ISSUE TITLE
[Enhancement] Add an animations in skills using Itemadder/oraxen

### ISSUE THREAD

**Issue by Hitman477** [magemonkeystudio/fabled#849]
**Is your feature request related to a problem? Please describe.**
I think standart animations in Minecraft is odd. Thats why i will be happy to see a new animations when players using skills

**Describe the solution you'd like**
Add a mechanic called animation that will import an animation from itemadder or oraxen

**Describe alternatives you've considered**
Idk

**Additional context**
This would be banger

**Comment by Travja** [comment]
Are these animations standalone things or are they actually items? I'll not sure how Oraxen or ItemsAdder work

**Comment by Hitman477** [comment]
It using Resource pask where you can upload custom animation. https://itemsadder.devs.beer/plugin-usage/adding-content/mobs/advanced-method/animations

**Comment by Travja** [comment]
So to be clear, you can modify entity animations with ItemsAdder by modifying the resource pack, basically. Then you want a mechanic that plays those animations? Does ItemsAdder have a way on their side to trigger the animation?

**Comment by Hitman477** [comment]
Sadly, there is no API to trigger a player animation. But there is a command to do, so i think until devs from IA didn't implement this into their api, i should use command mechanic in PSApi
