### ISSUE TITLE
[Bug]: Placeholder’s Giving Unexpected Outcomes

### ISSUE THREAD

**Issue by RAYCAL2000** [magemonkeystudio/fabled#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

When using the placeholders that exclusively function if the player possesses data within the selected group, they don’t give the correct info. The biggest one being the %fabled_player_<groupname>_mainclass% placeholder. When run it gives the same value as the %fabled_default_currentclassname% placeholder.

For example if I have two groups “Class” and “Race” with the following classes in the groups “Berserker” (Class) and “Merfolk” (Race). If you run /papi parse me %fabled_player_class_mainclass% you get Bersrker. If you run /papi parse me %fabled_player_race_mainclass% you also get Berserker.

### Expected Behavior

If you run %fabled_player_race_mainclass% you should get the value Merfolk returned.

### Steps To Reproduce

1. Create two groups with the names “Class” and “Race”
2. Create two classes, one in each group.
3. Make sure both “Class” and “Race” are professed.
4. Run the /papi parse me %fabled_player_class_mainclass%
5. Should return the name of your current “Class”
6. Run the /papi parse me %fabled_player_race_mainclass%
7. Should return the name of your current “Race”

### Environment

```markdown
- Server Software: 1.20.6
- Fabled Version: 1.0.0-R1
- Codex Version: 1.0.0-R1
- Plugins: Codex, Divinity, Fabled, AdvancedSkills, BetonQuest, ChatControlRed, CodexRPG, CustomNameplates, FabledEnchants, FabledParties, FastAsyncWorldEdit, Genesis, LibsDisguises, LuckPerms, *MultipleCurrencies, MythicDungeons, MythicMobs, Oraxen, packetevents, PlaceholderAPI, PlugManX, ProtocolLib, spark, Vault, ViaBackwards, ViaVersion
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

### Anything else?

There may be a different placeholder than I should be using, but I pulled all the information I saw before. Also I know that I do not have the most up to date version of the plugin, but there were no mentions of placeholders being fixed in any of the updates that have come out as of recent!

**Comment by Travja** [comment]
Use `%fabled_player_<name>_class%` to get the class name for the group. Mainclass returns the class name for the main class (which is typically class).
